language: ruby
rvm:
  - 2.3
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
before_install:
- gem update bundler
script:
  - RAILS_ENV=test bundle exec rake app:db:create app:db:migrate
  - bundle exec rspec
  - RAILS_ENV=test bundle exec rake app:db:drop
before_script:
- cp spec/dummy/config/database.yml.ci spec/dummy/config/database.yml
- psql -c 'create database g5_authenticatable_test;' -U postgres
