development:
  adapter: postgresql
  encoding: unicode
  database: devise_g5_authenticatable_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: devise_g5_authenticatable_test
  pool: 5
